import type { Metadata } from 'next';
import { Header, Footer } from '@/components/organisms';
import { Pretendard, TossFace } from '@/assets/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={`${Pretendard.variable} ${TossFace.variable}`}>
      <body>
        <div className='flex min-h-screen flex-col'>
          <Header />
          <main className='mx-auto w-[1440px] grow p-9'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
