import type { Metadata } from 'next';
import Script from 'next/script';
import { Header, Footer } from '@/components/organisms';
import { Pretendard, TossFace } from '@/assets/fonts';
import './globals.css';
import { KAKAO_API_KEY } from '@/constants/baseUrl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={`${Pretendard.variable} ${TossFace.variable}`}>
      <body>
        <div className='flex min-h-screen flex-col'>
          <Header />
          <main className='mx-auto w-[1440px] grow p-9'>{children}</main>
          <Footer />
        </div>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_API_KEY}&libraries=services,clusterer&autoload=false`}
          strategy='beforeInteractive'
        />
      </body>
    </html>
  );
}
